version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    #    environment:
    #      MONGO_INITDB_ROOT_USERNAME: vlad
    #      MONGO_INITDB_ROOT_PASSWORD: secret
    env_file:
      - ./env/mongo.env
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
  backend:
    build: ./backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
      - ./backend:/app/backend
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
    environment:
      NODE_OPTIONS: --openssl-legacy-provider

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
    environment:
      NODE_OPTIONS: --openssl-legacy-provider

volumes:
  data:
  logs: